services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mediscreen'
      MYSQL_USER: 'eliott'
      MYSQL_PASSWORD: 'datasperger'
      MYSQL_ROOT_PASSWORD: '1048576'
    ports:
      - '3307:3306'
    expose:
      - '3306'
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: '1048576'
    ports:
      - "27017:27017"

